[package]
name = "rockplacer"
version = "0.1.0"
authors = ["Syver <syver.storm.furru@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
edge-detection = "0.2.4"
image = "0.22.0"
rand = "0.7.3"
